// angular/src/app/_core/components/product-card/product-card.component.ts
import { Component, Input } from '@angular/core';
import { Product } from '../../models';

@Component({
  selector: 'app-product-card',
  standalone: true,
  templateUrl: './product-card.component.html',
})
export class ProductCardComponent {
  @Input() product?: Product;

  get formattedOriginalPrice(): string {
    return 'test';
  }

  get formattedDiscountedPrice(): string {
    return 'test';
  }
}

<div class="group relative" data-cy="product-card">
  <div
    v-if="hasDiscount"
    class="absolute top-3 right-3 z-10"
    data-cy="product-card__discount-pill"
  >
    <span
      class="bg-red-500 rounded-md px-2.5 py-1.5 text-sm font-semibold text-white"
    >
      {{ product?.discount }}%
    </span>
  </div>
  <div
    class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-xl bg-gray-200 border border-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80"
  >
    <img
      src="https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg"
      alt="Front of men&#039;s Basic Tee in black."
      class="h-full w-full object-cover object-center lg:h-full lg:w-full"
      data-cy="product-card__image"
    />
  </div>
  <div class="mt-4 flex justify-between">
    <div>
      <h3
        class="text-md font-bold text-gray-700 pr-4 line-clamp-1"
        data-cy="product-card__title"
      >
        <a href="#">
          <span aria-hidden="true" class="absolute inset-0"></span>
          {{ product?.name }}
        </a>
      </h3>
      <p
        class="font-sm text-gray-500 line-clamp-1 pr-4"
        data-cy="product-card__description"
      >
        {{ product?.description }}
      </p>
    </div>
    <div class="flex flex-col flex-shrink-0 justify-start">
      <s
        v-show="hasDiscount"
        class="text-gray-500 text-sm text-end"
        data-cy="product-card__original-price"
      >
        {{ formattedOriginalPrice }}
      </s>
      <p
        class="text-md font-bold text-gray-900"
        data-cy="product-card__discounted-price"
      >
        {{ formattedDiscountedPrice }}
      </p>
    </div>
  </div>
</div>

// vue/components/ProductCard.vue
<template>
  <div class="group relative" data-cy="product-card">
    <div
      v-if="hasDiscount"
      class="absolute top-3 right-3 z-10"
      data-cy="product-card__discount-pill"
    >
      <span class="bg-red-500 rounded-md px-2.5 py-1.5 text-sm font-semibold text-white">
        {{ discount }}%
      </span>
    </div>
    <div
      class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-xl bg-gray-200 border border-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80"
    >
      <img
        src="https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg"
        alt="Front of men&#039;s Basic Tee in black."
        class="h-full w-full object-cover object-center lg:h-full lg:w-full"
        data-cy="product-card__image"
      />
    </div>
    <div class="mt-4 flex justify-between">
      <div>
        <h3 class="text-md font-bold text-gray-700 pr-4 line-clamp-1" data-cy="product-card__title">
          <a href="#">
            <span aria-hidden="true" class="absolute inset-0"></span>
            {{ props.name }}
          </a>
        </h3>
        <p class="font-sm text-gray-500 line-clamp-1 pr-4" data-cy="product-card__description">
          {{ props.description }}
        </p>
      </div>
      <div class="flex flex-col flex-shrink-0 justify-start">
        <s
          v-show="hasDiscount"
          class="text-gray-500 text-sm text-end"
          data-cy="product-card__original-price"
        >
          {{ formattedOriginalPrice }}
        </s>
        <p class="text-md font-bold text-gray-900" data-cy="product-card__discounted-price">
          {{ formattedDiscountedPrice }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { formatCurrencyToIDR, calculatePriceWithDiscount } from '@/utils'
const props = defineProps({
  name: {
    type: String,
    default: ''
  },
  description: {
    type: String,
    default: ''
  },
  originalPrice: {
    type: Number,
    default: 0
  },
  discount: {
    type: Number,
    default: 0
  }
})

const hasDiscount = computed(() => props.discount > 0)

const formattedOriginalPrice = computed(() => {
  return formatCurrencyToIDR(props.originalPrice)
})

const formattedDiscountedPrice = computed(() => {
  const discountedPrice = calculatePriceWithDiscount(props.originalPrice, props.discount)
  return formatCurrencyToIDR(discountedPrice)
})
</script>
